# Generated by Django 4.2 on 2023-05-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artigoprincipal',
            old_name='conteudo',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='artigosecundario',
            old_name='conteudo',
            new_name='texto',
        ),
    ]
