# Generated by Django 4.2 on 2023-05-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_conteudo_artigoprincipal_texto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtigoTerceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
            ],
        ),
    ]
