# Generated by Django 4.2 on 2023-05-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230504_0757'),
    ]

    operations = [
    ]
