# Generated by Django 4.2 on 2023-05-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_artigoprincipal_imagem_artigoterceiro_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigoprincipal',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='templates/home/media'),
        ),
        migrations.AlterField(
            model_name='artigosecundario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='templates/home/media'),
        ),
        migrations.AlterField(
            model_name='artigosgenericos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='artigoterceiro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='templates/home/media'),
        ),
    ]
