# Generated by Django 5.1.3 on 2024-11-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_category_tag_artigoprincipal_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artigosecundario',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='artigosecundario',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='artigosgenericos',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='artigosgenericos',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='artigosrecommends',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='artigosrecommends',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='artigoterceiro',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='artigoterceiro',
            name='tags',
        ),
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('principal', 'Principal'), ('secundario', 'Secundário'), ('terciario', 'Terciário'), ('generico', 'Genérico'), ('recomendado', 'Recomendado')], max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('categories', models.ManyToManyField(blank=True, to='home.category')),
                ('tags', models.ManyToManyField(blank=True, to='home.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='ArtigoPrincipal',
        ),
        migrations.DeleteModel(
            name='ArtigoSecundario',
        ),
        migrations.DeleteModel(
            name='ArtigosGenericos',
        ),
        migrations.DeleteModel(
            name='ArtigosRecommends',
        ),
        migrations.DeleteModel(
            name='ArtigoTerceiro',
        ),
    ]
